FROM xrdp2
MAINTAINER Guenther Stangassinger

RUN apt-get -y update
RUN apt-get -yy upgrade
RUN apt-get -yy install \
         geany pkg-config unzip tar
                      
         
         



ADD tmp /tmp
WORKDIR /tmp
#RUN tar -xvf Quartus-lite-17.1.0.590-linux.tar





